# Generated by Django 2.1.5 on 2019-01-26 11:35

from django.db import migrations, models
import django.db.models.deletion
import upcoming_events.models
from django.core.files import File

def create_icons(apps, schema_editor):
    from upcoming_events.models import EventIcon
    ListOfIcons = [["ESS", "ess-logo.png"], ["DMSC", "dmsc.png"], ["ECDC", "ecdc.png"], ["Screaming Udder", "screaming_udder.png"]]
    for Icon in ListOfIcons:
        ImageFile = open("upcoming_events/static/images/" + Icon[1], "rb")
        ImageData = File(ImageFile)
        CurrentIcon = EventIcon()
        CurrentIcon.Name = Icon[0]
        CurrentIcon.Image.save(Icon[1], ImageData, save=True)
        CurrentIcon.save()

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200)),
                ('Description', models.TextField(blank=True, null=True)),
                ('StartDate', models.DateTimeField(default=upcoming_events.models.todayMorning, verbose_name='Start of event')),
                ('EndDate', models.DateTimeField(default=upcoming_events.models.todayAfternoon, null=True, verbose_name='End of event')),
            ],
        ),
        migrations.CreateModel(
            name='EventIcon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Image', models.FileField(upload_to='icon_images/')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='Icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='upcoming_events.EventIcon'),
        ),
        migrations.RunPython(create_icons)
    ]
