# Generated by Django 3.0.2 on 2020-01-14 10:15

from django.db import migrations, models
import django.utils.timezone
from maxims.import_maxims import add_known_maxims

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maxim',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('CreationDate', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Time of addition to database')),
                ('Text', models.CharField(max_length=2000)),
            ],
        ),
        migrations.RunPython(add_known_maxims)
    ]
